### ISSUE TITLE
Atualizar imagem do slide 90

### ISSUE THREAD

**Issue by fgsl** [fgsl/lojasacme#45]
A imagem não reflete a página. Execute a aplicação, capture a tela e substitua pela correta.

**Comment by AlexLealMoura** [comment]
tomei a liberdade de dar um zoom na pagina, pois na hora de tirar o print a imagem ficava muito larga, e para não diminuir a qualidade dela optei por tirar o print com um zoom de 150%.

**Comment by fgsl** [comment]
> tomei a liberdade de dar um zoom na pagina, pois na hora de tirar o print a imagem ficava muito larga, e para não diminuir a qualidade dela optei por tirar o print com um zoom de 150%.

Muito bom.
