### ISSUE TITLE
Eliminar expressão "else" onde não for necessário

### ISSUE THREAD

**Issue by fgsl** [fgsl/lojasacme#80]
O relatório do phpmd indica que os seguintes métodos tem a expressão "else" onde não é necessária. Verificar e refazer o código usando apenas if no lugar de if...else... se for possível.

**lojasacme/module/Application/src/Controller/EstoqueController.php**

- loginAction
- manterProdutoAction
- alterarPrecoAction
- alterarNomeAction
- excluirAction
- incluirProdutoAction

**lojasacme/module/Application/src/Controller/IndexController.php**

- loginAction

Em adição, considere se os métodos loginAction de ambas as classes não podem ser reunidos em uma única classe abstrata.

**Comment by AlexLealMoura** [comment]
O único método do qual não tirei o else, foi o método de excluir produto, pois isso resultava em uma mensagem de erro, que dizia que tal produto, consta na lista de pedidos, mesmo que isso não fosse verdade.

E em relação aos métodos de login, imagino que não seja possível uni-los pois as tabelas de usuários e administradores são separadas.
