### ISSUE TITLE
Verificar se variáveis estão sendo usadas

### ISSUE THREAD

**Issue by fgsl** [fgsl/lojasacme#83]
Verificar se as variáveis abaixo estão sendo usadas, caso contrário, remova-as dos respectivos métodos.

lojasacme/module/Application/src/Controller/CarrinhoController.php:126	
**$produto**
lojasacme/module/Application/src/Controller/CarrinhoController.php:185	
**$sessionManager**
lojasacme/module/Application/src/Controller/EstoqueController.php:67
**$where.**
lojasacme/module/Application/src/Model/Produto.php:17
**$codigo**
lojasacme/module/Application/src/Model/UsuarioTable.php:37
**$usuario**
lojasacme/module/Application/test/Controller/CarrinhoControllerTest.php:17
**$carrinho**
lojasacme/module/Application/test/Model/ProdutoTableTest.php:23
$container

**Comment by AlexLealMoura** [comment]
A única variável que aparentemente estava sendo utilizada era $produto do carrinhoControler, ela serve como iterador, pois o foreach procura um produto cuja chave e id sejam idêntico e então troca a quantidade do produto pela quantidade entregue no formulário.
