### ISSUE TITLE
Corrigir erro na execução dos testes automatizados

### ISSUE THREAD

**Issue by fgsl** [fgsl/lojasacme#84]
Ao rodar os testes com vendor/bin/phpunit ocorre o seguinte erro:

`PHP Fatal error:  Declaration of ApplicationTest\Controller\CarrinhoControllerTest::setUp() must be compatible with Zend\Test\PHPUnit\Controller\AbstractControllerTestCase::setUp(): void in /var/www/html/lojasacme/module/Application/test/Controller/CarrinhoControllerTest.php on line 15
`

**Comment by AlissonBM** [comment]
Corrigida pela tarefa #89
