### ISSUE TITLE
Remover imagens do controle de versão

### ISSUE THREAD

**Issue by fgsl** [fgsl/lojasacme#85]
As imagens dos produtos estão ligadas aos registros da tabela no banco de dados.
Elas não devem ser versionadas.
Apague as imagens do controle de versão.
Apague também o arquivo sem nome lojasacme/.png

**Comment by AlexLealMoura** [comment]
o seguinte trecho foi adicionado ao arquivo .gitignore "public/img/produtos", caso as imagens continuem sendo versionadas irei reabrir a tarefa.
